-- UI changes do not take effect immediately. Any attempt to query the contents of the XML will return stale results until loading returns to false.

local xmlTable = {
    {
        tag="Defaults",
        children={
            {
                tag="TableLayout",
                attributes={
                    cellBackgroundColor="clear",
                    rowBackgroundColor="#942d28",
                    width="1000",
                    height="850",
                    columnWidths="80 840 80",
                    useGlobalCellPadding="false",
                    raycastTarget="1",
                },
            },
            {
                tag="Button",
                attributes={
                    ignoreLayout="true",
                    fontStyle="Bold",
                    textColor="#373737",
                    colors="#f0eddc|#fffceb|#dedbcb|#A3A19670",
                    fontSize="20",
                    shadow="#00000099",
                    shadowDistance="3 -3",
                },
            },
            {
                tag="Toggle",
                attributes={
                    ignoreLayout="true",
                    toggleWidth="25",
                    toggleHeight="25",
                    rectAlignment="MiddleRight",
                    offsetXY="-45 0",
                },
            },
            {
                tag="Tooltip",
                attributes={
                    tooltipTextColor="#bf161c",
                    tooltipBorderColor="#942d28",
                    tooltipBackgroundColor="#f0eddc",
                    tooltipPosition="Below",
                    tooltipOffset="5",
                },
            },
            {
                tag="Image",
                attributes={
                    class="carouselImage",
                    shadow="#00000099",
                    shadowDistance="3 -3",
                    preserveAspect="true",
                    onClick="ScenarioClick",
                    tooltip="Selected scenario to play. Difficulty generally ranging from A for beginners to E for experts. (Click for backside)",
                    tooltipOffset="-200",
                },
            },
            {
                tag="Text",
                attributes={
                    fontSize="15",
                    fontStyle="Italic",
                    color="#f0eddc",
                    alignment="MiddleLeft",
                },
            },
            {
                tag="Text",
                attributes={
                    class="checkbox",
                    fontSize="18",
                    fontStyle="Bold",
                    alignment="MiddleCenter",
                },
            },
        },
    },
    {
        tag="TableLayout",
        attributes={
            id="setupWindow",
        },
        children={
            {
                tag="Row",
                attributes={
                    preferredHeight="200",
                },
                children={
                    {
                        tag="Cell"
                    },
                    {
                        tag="Cell",
                        attributes={
                            padding="0 0 0 10"
                        },
                        children={
                            {
                                tag="Image",
                                attributes={
                                    image="Banner_Image",
                                    preserveAspect="true",
                                },
                            },
                        },
                    },
                    {
                        tag="Cell",
                        children={
                            {
                                tag="Button",
                                attributes={
                                    onClick="ButtonCloseWindowClick",
                                    tooltip="Skip setup and just look around",
                                    rectAlignment="UpperRight",
                                    width="40",
                                    height="40",
                                },
                                value="X"
                            },
                        },
                    },
                },
            },
            {
                tag="Row",
                attributes={
                    preferredHeight="40",
                },
                children={
                    {
                        tag="Cell"
                    },
                    {
                        tag="Cell",
                        children={
                            {
                                tag="Toggle",
                                attributes={
                                    id="toggleAchievements",
                                    tooltip="Adds 4 Sawyer, 2 Desperation, 2 Injury and 2 item cards to the game. Only recommended for experienced players!",
                                    onValueChanged="ToggleAchievementsChanged",
                                },
                            },
                            {
                                tag="Text",
                                    attributes={
                                        class="checkbox"
                                    },
                                    value="Use Achievement Cards"
                            },
                        },
                    },
                    {
                        tag="Cell"
                    },
                },
            },
            {
                tag="Row",
                children={
                    {
                        tag="Cell",
                        children={
                            {
                                tag="Button",
                                attributes={
                                    id="buttonScenarioLeft",
                                    interactable="false",
                                    onClick="ButtonScenarioLeftClick",
                                    icon="Button_Icon_Left",
                                    width="70",
                                    height="70",
                                }
                            }
                        },
                    },
                    {
                        tag="Cell",
                        attributes={
                            padding="10 10 0 20",
                        },
                        children={
                            {
                                tag="Image",
                                attributes={
                                    class="carouselImage",
                                    id="scenario_Carousel",
                                    image="Scenario_A_Front",
                                },
                            },
                        },
                    },
                    {
                        tag="Cell",
                        children={
                            {
                                tag="Button",
                                attributes={
                                    id="buttonScenarioRight",
                                    tooltip="Next Scenario", 
                                    onClick="ButtonScenarioRightClick",
                                    icon="Button_Icon_Right",
                                    width="70",
                                    height="70",
                                }
                            },
                        },
                    },
                },
            },
            {
                tag="Row",
                attributes={
                    preferredHeight="70",
                },
                children={
                    {
                        tag="Cell"
                    },
                    {
                        tag="Cell",
                        children={
                            tag="Button",
                            attributes={
                                onClick="ButtonStartGameClick",
                                width="170",
                                height="60"
                            },
                            value="Start Game",
                        }
                    },
                    {
                        tag="Cell",
                        attributes={
                            width="300",
                        },
                        children={
                            {
                                tag="Text",
                                value="Made by: Freich"
                            }
                        }
                    }
                }
            }
        }
    }
}

function SetXmlTable()
    UI.setXmlTable(xmlTable)
    log("Set XML")
end